services:
  - type: web
    name: vector-war
    env: node
    plan: free

    buildCommand: npm install && npm run install:all && cd frontend && npm install && npm run build

    startCommand: node backend/server.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: PUBLIC_API_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        sync: false
